/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pages: Page;
    categories: Category;
    media: Media;
    software_types: SoftwareType;
    tags: Tag;
    product_previews: ProductPreview;
    product_files: ProductFile;
    products: Product;
    seller_profiles: SellerProfile;
    wallets: Wallet;
    wallet_ledger: WalletLedger;
    payment_intents: PaymentIntent;
    payment_transactions: PaymentTransaction;
    payment_webhook_events: PaymentWebhookEvent;
    orders: Order;
    order_items: OrderItem;
    entitlements: Entitlement;
    download_events: DownloadEvent;
    seller_earnings: SellerEarning;
    withdrawals: Withdrawal;
    withdrawal_events: WithdrawalEvent;
    refunds: Refund;
    reviews: Review;
    comments: Comment;
    tickets: Ticket;
    moderation_cases: ModerationCase;
    forms: Form;
    'form-submissions': FormSubmission;
    addresses: Address;
    transactions: Transaction;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    users: {
      orders: 'orders';
      addresses: 'addresses';
    };
    orders: {
      items: 'order_items';
      earnings: 'seller_earnings';
    };
    withdrawals: {
      events: 'withdrawal_events';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    software_types: SoftwareTypesSelect<false> | SoftwareTypesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    product_previews: ProductPreviewsSelect<false> | ProductPreviewsSelect<true>;
    product_files: ProductFilesSelect<false> | ProductFilesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    seller_profiles: SellerProfilesSelect<false> | SellerProfilesSelect<true>;
    wallets: WalletsSelect<false> | WalletsSelect<true>;
    wallet_ledger: WalletLedgerSelect<false> | WalletLedgerSelect<true>;
    payment_intents: PaymentIntentsSelect<false> | PaymentIntentsSelect<true>;
    payment_transactions: PaymentTransactionsSelect<false> | PaymentTransactionsSelect<true>;
    payment_webhook_events: PaymentWebhookEventsSelect<false> | PaymentWebhookEventsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    order_items: OrderItemsSelect<false> | OrderItemsSelect<true>;
    entitlements: EntitlementsSelect<false> | EntitlementsSelect<true>;
    download_events: DownloadEventsSelect<false> | DownloadEventsSelect<true>;
    seller_earnings: SellerEarningsSelect<false> | SellerEarningsSelect<true>;
    withdrawals: WithdrawalsSelect<false> | WithdrawalsSelect<true>;
    withdrawal_events: WithdrawalEventsSelect<false> | WithdrawalEventsSelect<true>;
    refunds: RefundsSelect<false> | RefundsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    comments: CommentsSelect<false> | CommentsSelect<true>;
    tickets: TicketsSelect<false> | TicketsSelect<true>;
    moderation_cases: ModerationCasesSelect<false> | ModerationCasesSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    addresses: AddressesSelect<false> | AddressesSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    commission_settings: CommissionSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    commission_settings: CommissionSettingsSelect<false> | CommissionSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
  /**
   * Generated by the Payload Ecommerce plugin
   */
  ecommerce: {
    collections: {
      addresses: Address;
      customers?: User;
      products: Product;
      transactions: Transaction;
    };
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  roles?: ('admin' | 'buyer' | 'seller' | 'moderator' | 'financeAdmin')[] | null;
  orders?: {
    docs?: (number | Order)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  addresses?: {
    docs?: (number | Address)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Đơn hàng kỹ thuật số (Digital Orders - Immutable Snapshot Price)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  /**
   * Mã định danh duy nhất của đơn hàng (VD: ORD-20260915-XXXXX)
   */
  code: string;
  buyer: number | User;
  /**
   * Tổng giá trị đơn hàng tính theo VND
   */
  totalAmount: number;
  currency: 'VND';
  status: 'PENDING' | 'COMPLETED' | 'CANCELLED' | 'REFUNDED';
  paymentSource: 'wallet' | 'free';
  /**
   * Thời điểm hoàn tất thanh toán và cấp quyền sở hữu
   */
  paidAt?: string | null;
  /**
   * Ghi chú nội bộ hoặc thông tin bổ sung về đơn hàng
   */
  notes?: string | null;
  items?: {
    docs?: (number | OrderItem)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  earnings?: {
    docs?: (number | SellerEarning)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Chi tiết sản phẩm đơn hàng snapshot bất biến (BR-07)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order_items".
 */
export interface OrderItem {
  id: number;
  order: number | Order;
  product: number | Product;
  seller: number | User;
  /**
   * Giá bán snapshot tại thời điểm đặt hàng (BR-07)
   */
  salePrice: number;
  /**
   * Phí hoa hồng sàn thu
   */
  platformFee: number;
  /**
   * Số tiền thực nhận của người bán (salePrice - platformFee - tax)
   */
  sellerAmount: number;
  /**
   * Thuế áp dụng
   */
  tax: number;
  /**
   * Phiên bản chính sách phân chia doanh thu áp dụng tại thời điểm giao dịch
   */
  policyVersion: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Public watermarked previews (images, PDF sample sheets, 3D models)
   */
  previewGallery?: (number | ProductPreview)[] | null;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  layout?: (CallToActionBlock | ContentBlock | MediaBlock)[] | null;
  /**
   * Price in Vietnamese Dong (VND). Set to 0 if free.
   */
  price: number;
  /**
   * Mark as free asset (displays "Tải miễn phí" CTA)
   */
  isFree?: boolean | null;
  technicalSpecs?: {
    fileFormat?: string | null;
    softwareVersion?: string | null;
    fileSize?: string | null;
    unit?: ('metric' | 'imperial' | 'other') | null;
  };
  relatedProducts?: (number | Product)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  categories?: (number | Category)[] | null;
  software_types?: (number | SoftwareType)[] | null;
  tags?: (number | Tag)[] | null;
  /**
   * Tài khoản người bán sở hữu tài nguyên này
   */
  seller?: (number | null) | User;
  /**
   * Tệp bản vẽ gốc riêng tư (Private originals - BR-06)
   */
  originalFiles?: (number | ProductFile)[] | null;
  /**
   * Trạng thái quy trình kiểm duyệt (FR-28 & BR-08)
   */
  moderationStatus?: ('draft' | 'submitted' | 'in_review' | 'changes_requested' | 'approved' | 'rejected') | null;
  /**
   * Lý do yêu cầu sửa hoặc từ chối từ ban kiểm duyệt
   */
  moderationNotes?: string | null;
  moderationHistory?:
    | {
        reviewer?: (number | null) | User;
        action?: ('submitted' | 'in_review' | 'changes_requested' | 'approved' | 'rejected') | null;
        note?: string | null;
        timestamp?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Cam kết có quyền sở hữu hợp pháp đối với tài nguyên số này
   */
  copyrightDeclared?: boolean | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product_previews".
 */
export interface ProductPreview {
  id: number;
  title: string;
  previewImage: number | Media;
  previewType: 'image' | 'pdf' | 'model_viewer';
  isWatermarked?: boolean | null;
  caption?: string | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  publishedOn?: string | null;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?: {
              relationTo: 'pages';
              value: number | Page;
            } | null;
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  layout: (
    | CallToActionBlock
    | ContentBlock
    | MediaBlock
    | ArchiveBlock
    | CarouselBlock
    | ThreeItemGridBlock
    | BannerBlock
    | FormBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'products' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'products';
        value: number | Product;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  description?: string | null;
  parent?: (number | null) | Category;
  icon?: (number | null) | Media;
  image?: (number | null) | Media;
  sortOrder?: number | null;
  status?: ('active' | 'archived') | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselBlock".
 */
export interface CarouselBlock {
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'products' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'products';
        value: number | Product;
      }[]
    | null;
  /**
   * This field is auto-populated after-read
   */
  populatedDocs?:
    | {
        relationTo: 'products';
        value: number | Product;
      }[]
    | null;
  /**
   * This field is auto-populated after-read
   */
  populatedDocsTotal?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'carousel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ThreeItemGridBlock".
 */
export interface ThreeItemGridBlock {
  products?: (number | Product)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'threeItemGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "software_types".
 */
export interface SoftwareType {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  icon?: (number | null) | Media;
  /**
   * File extensions supported by this software type (e.g. .dwg, .rvt, .skp)
   */
  fileExtensions?: string[] | null;
  description?: string | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product_files".
 */
export interface ProductFile {
  id: number;
  seller: number | User;
  /**
   * Tên file gốc người bán tải lên
   */
  originalFilename?: string | null;
  /**
   * Định dạng tệp (ví dụ: .dwg, .rvt, .zip)
   */
  fileFormat?: string | null;
  /**
   * Mã băm SHA-256 xác thực tính toàn vẹn của tệp
   */
  checksum?: string | null;
  /**
   * Dung lượng tệp tính bằng bytes
   */
  fileSize?: number | null;
  virusScanStatus?: ('pending' | 'clean' | 'quarantined') | null;
  status?: ('UPLOADING' | 'PROCESSING' | 'READY' | 'FAILED' | 'QUARANTINED') | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Sổ cái doanh thu người bán và chính sách giữ tiền (Seller Earnings - PLAN.md FR-31, BR-03)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seller_earnings".
 */
export interface SellerEarning {
  id: number;
  seller: number | User;
  order: number | Order;
  /**
   * Mục đơn hàng tương ứng (đảm bảo tính duy nhất 1-1, tránh trùng lặp doanh thu)
   */
  orderItem: number | OrderItem;
  product: number | Product;
  /**
   * Giá bán của sản phẩm tại thời điểm giao dịch (snapshot)
   */
  salePrice: number;
  /**
   * Phí hoa hồng nền tảng (salePrice * commissionRate)
   */
  platformFee: number;
  /**
   * Doanh thu chuyển cho người bán (salePrice - platformFee - tax)
   */
  sellerAmount: number;
  /**
   * Thuế snapshot tại thời điểm giao dịch (không tính trong P0, mặc định 0)
   */
  tax: number;
  /**
   * Tỷ lệ chiết khấu snapshot tại thời điểm giao dịch (BR-07)
   */
  commissionRate: number;
  currency: 'VND';
  /**
   * Vòng đời: PENDING -> AVAILABLE -> PAID (hoặc REVERSED nếu hoàn tiền)
   */
  status: 'PENDING' | 'AVAILABLE' | 'REVERSED' | 'PAID';
  /**
   * Số ngày giữ tiền tạm thời trước khi chuyển thành khả dụng (mặc định 7 ngày)
   */
  holdPeriodDays: number;
  /**
   * Thời điểm thu nhập tự động chuyển sang AVAILABLE (createdAt + holdPeriodDays)
   */
  holdUntil: string;
  /**
   * Thời điểm thu nhập thực tế chuyển sang trạng thái AVAILABLE
   */
  availableAt?: string | null;
  /**
   * Thời điểm hoàn tất chi trả tiền cho người bán qua yêu cầu rút tiền
   */
  paidAt?: string | null;
  /**
   * Thời điểm đơn hàng bị hoàn trả và thu nhập bị đảo ngược
   */
  reversedAt?: string | null;
  /**
   * Phiên bản chính sách chiết khấu hoa hồng snapshot
   */
  policyVersion: string;
  /**
   * Ghi chú nội bộ, lý do hoàn trả hoặc mã đối soát
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses".
 */
export interface Address {
  id: number;
  customer?: (number | null) | User;
  title?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  company?: string | null;
  addressLine1?: string | null;
  addressLine2?: string | null;
  city?: string | null;
  state?: string | null;
  postalCode?: string | null;
  country:
    | 'US'
    | 'GB'
    | 'CA'
    | 'AU'
    | 'AT'
    | 'BE'
    | 'BR'
    | 'BG'
    | 'CY'
    | 'CZ'
    | 'DK'
    | 'EE'
    | 'FI'
    | 'FR'
    | 'DE'
    | 'GR'
    | 'HK'
    | 'HU'
    | 'IN'
    | 'IE'
    | 'IT'
    | 'JP'
    | 'LV'
    | 'LT'
    | 'LU'
    | 'MY'
    | 'MT'
    | 'MX'
    | 'NL'
    | 'NZ'
    | 'NO'
    | 'PL'
    | 'PT'
    | 'RO'
    | 'SG'
    | 'SK'
    | 'SI'
    | 'ES'
    | 'SE'
    | 'CH';
  phone?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seller_profiles".
 */
export interface SellerProfile {
  id: number;
  user: number | User;
  displayName: string;
  bio?: string | null;
  avatar?: (number | null) | Media;
  phone?: string | null;
  payoutInfo?: {
    bankName?: string | null;
    accountNumber?: string | null;
    accountHolderName?: string | null;
  };
  sellerTermsAccepted: boolean;
  sellerTermsAcceptedAt?: string | null;
  /**
   * Tỷ lệ hoa hồng sàn áp dụng riêng cho người bán (0.00 - 1.00, VD: 0.20 = 20%). Nếu để trống sẽ sử dụng tỷ lệ mặc định toàn sàn (30%).
   */
  commissionRate?: number | null;
  status?: ('pending' | 'active' | 'suspended' | 'rejected') | null;
  totalSales?: number | null;
  rating?: number | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Số dư ví người dùng (Chỉ đọc - Mọi biến động phải qua Money Write Path và Ledger)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wallets".
 */
export interface Wallet {
  id: number;
  user: number | User;
  balance: number;
  pendingBalance: number;
  currency: 'VND';
  status: 'active' | 'frozen' | 'closed';
  updatedAt: string;
  createdAt: string;
}
/**
 * Sổ cái tài chính bất biến (Append-Only Ledger - Không thể sửa hoặc xóa)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wallet_ledger".
 */
export interface WalletLedger {
  id: number;
  wallet: number | Wallet;
  user: number | User;
  type: 'topup' | 'purchase' | 'refund' | 'adjustment' | 'withdrawal' | 'payout';
  amount: number;
  direction: 'credit' | 'debit';
  referenceType: 'payment_intent' | 'order' | 'adjustment' | 'withdrawal' | 'system';
  referenceId: string;
  balanceBefore: number;
  balanceAfter: number;
  description?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Ý định thanh toán / Nạp tiền người dùng (Payment Intents State Machine)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment_intents".
 */
export interface PaymentIntent {
  id: number;
  code: string;
  user: number | User;
  provider: 'sepay' | 'vnpay' | 'momo';
  amount: number;
  currency: 'VND';
  status: 'CREATED' | 'PENDING' | 'PAID' | 'EXPIRED' | 'FAILED' | 'CANCELLED' | 'REFUNDED';
  reconciliationFlag?: boolean | null;
  reconciliationNote?: string | null;
  expiresAt: string;
  checkoutUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Lịch sử giao dịch từ nhà cung cấp thanh toán (SePay) - Ràng buộc duy nhất BR-02
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment_transactions".
 */
export interface PaymentTransaction {
  id: number;
  paymentIntent: number | PaymentIntent;
  user: number | User;
  provider: string;
  providerTransactionId: string;
  amount: number;
  rawReference?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status: 'SUCCESS' | 'FAILED' | 'PENDING';
  paidAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Nhật ký sự kiện Webhook từ cổng thanh toán (Đã che giấu dữ liệu nhạy cảm)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment_webhook_events".
 */
export interface PaymentWebhookEvent {
  id: number;
  provider: string;
  eventId?: string | null;
  payload:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  headers?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  signatureValid: boolean;
  status: 'processed' | 'duplicate_ignored' | 'amount_mismatch' | 'invalid_signature' | 'failed';
  processedAt: string;
  errorDetails?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Sổ cái quyền sở hữu và tải tài nguyên số (Entitlements Ledger - PLAN.md FR-16, Decision 0006)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entitlements".
 */
export interface Entitlement {
  id: number;
  /**
   * Người dùng sở hữu quyền tải
   */
  user: number | User;
  /**
   * Sản phẩm được cấp quyền
   */
  product: number | Product;
  /**
   * Đơn hàng mua sản phẩm (để trống nếu là tải miễn phí)
   */
  order?: (number | null) | Order;
  /**
   * Mục đơn hàng liên kết (để trống nếu là tải miễn phí)
   */
  orderItem?: (number | null) | OrderItem;
  /**
   * Trạng thái quyền tải
   */
  status: 'active' | 'revoked' | 'expired';
  /**
   * Thời điểm cấp quyền
   */
  grantedAt: string;
  /**
   * Số lần đã tải file thành công
   */
  downloadCount: number;
  /**
   * Giới hạn số lần tải tối đa (để trống nếu không giới hạn)
   */
  maxDownloads?: number | null;
  /**
   * Thời điểm hết hạn tải (để trống nếu vĩnh viễn)
   */
  expiresAt?: string | null;
  /**
   * Thời điểm thu hồi quyền
   */
  revokedAt?: string | null;
  /**
   * Lý do thu hồi hoặc ghi chú cấp quyền
   */
  reason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Nhật ký kiểm toán lượt tải tệp riêng tư (Append-Only Audit Log - PLAN.md FR-17, Decision 0006)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "download_events".
 */
export interface DownloadEvent {
  id: number;
  /**
   * Người dùng thực hiện yêu cầu tải (để trống nếu là khách hoặc unauthenticated)
   */
  user?: (number | null) | User;
  /**
   * Sản phẩm được yêu cầu tải
   */
  product: number | Product;
  /**
   * Quyền sở hữu liên kết (để trống nếu bị từ chối trước khi xác thực quyền)
   */
  entitlement?: (number | null) | Entitlement;
  /**
   * Địa chỉ IP của client
   */
  ipAddress?: string | null;
  /**
   * User-Agent header của client
   */
  userAgent?: string | null;
  /**
   * Thời điểm ghi nhận lượt tải
   */
  downloadedAt: string;
  /**
   * Kết quả của yêu cầu tải
   */
  status: 'SUCCESS' | 'DENIED' | 'EXPIRED' | 'FAILED';
  /**
   * Mã băm SHA-256 của token một lần (phục vụ đối soát và chống replay)
   */
  downloadTokenHash?: string | null;
  /**
   * Nguyên nhân từ chối hoặc chi tiết lỗi kỹ thuật
   */
  errorReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Yêu cầu rút tiền của Người bán (Seller Withdrawals - FR-32, FLOW-U13)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "withdrawals".
 */
export interface Withdrawal {
  id: number;
  /**
   * Mã định danh duy nhất (VD: WTH-20260915-A1B2C3D4)
   */
  code: string;
  seller: number | User;
  /**
   * Số tiền rút (50.000 VND - 50.000.000 VND)
   */
  amount: number;
  currency: 'VND';
  status: 'REQUESTED' | 'UNDER_REVIEW' | 'APPROVED' | 'PROCESSING' | 'PAID' | 'REJECTED' | 'CANCELLED' | 'FAILED';
  bankInfo: {
    bankName: string;
    accountNumber: string;
    accountHolderName: string;
  };
  requestedAt: string;
  reviewedAt?: string | null;
  reviewedBy?: (number | null) | User;
  paidAt?: string | null;
  rejectionReason?: string | null;
  failureReason?: string | null;
  notes?: string | null;
  events?: {
    docs?: (number | WithdrawalEvent)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Nhật ký kiểm toán sự kiện rút tiền (Append-Only Audit Trail - PLAN.md §11.1)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "withdrawal_events".
 */
export interface WithdrawalEvent {
  id: number;
  withdrawal: number | Withdrawal;
  fromStatus?: string | null;
  toStatus: string;
  actor?: (number | null) | User;
  actorRole?: string | null;
  reason?: string | null;
  notes?: string | null;
  timestamp: string;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Lịch sử hoàn tiền và bút toán bù trừ (Refunds & Compensating Ledger - BR-03)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "refunds".
 */
export interface Refund {
  id: number;
  /**
   * Mã định danh duy nhất của giao dịch hoàn tiền (VD: REF-YYYYMMDD-XXXXX)
   */
  code: string;
  order: number | Order;
  orderItem: number | OrderItem;
  buyer: number | User;
  seller: number | User;
  amount: number;
  platformFeeRefunded: number;
  sellerAmountRefunded: number;
  currency: 'VND';
  reason: string;
  status: 'COMPLETED' | 'FAILED';
  processedBy: number | User;
  ledgerTransaction?: (number | null) | WalletLedger;
  entitlementRevoked?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Đánh giá và xếp hạng sản phẩm đã xác minh mua hàng (Reviews & Ratings - PLAN.md FR-20, BR-05)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  /**
   * Sản phẩm được đánh giá
   */
  product: number | Product;
  /**
   * Người mua gửi đánh giá
   */
  user: number | User;
  /**
   * Quyền sở hữu xác minh mua hàng (BR-05)
   */
  entitlement: number | Entitlement;
  /**
   * Đánh giá số sao (1 đến 5 sao)
   */
  rating: number;
  /**
   * Tiêu đề đánh giá (tùy chọn)
   */
  title?: string | null;
  /**
   * Nội dung nhận xét chi tiết (tối thiểu 5 ký tự)
   */
  content: string;
  /**
   * Trạng thái kiểm duyệt đánh giá
   */
  status: 'published' | 'pending' | 'rejected';
  sellerReply?: {
    comment?: string | null;
    repliedAt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Hỏi đáp & Bình luận sản phẩm (Q&A / Comments - PLAN.md FR-21)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments".
 */
export interface Comment {
  id: number;
  /**
   * Sản phẩm được bình luận
   */
  product: number | Product;
  /**
   * Người gửi bình luận
   */
  user: number | User;
  /**
   * Bình luận cha (nếu là câu trả lời 1 cấp)
   */
  parent?: (number | null) | Comment;
  /**
   * Nội dung bình luận / câu hỏi (tối thiểu 3 ký tự)
   */
  content: string;
  /**
   * Trạng thái kiểm duyệt bình luận
   */
  status: 'published' | 'pending' | 'hidden';
  /**
   * Đánh dấu phản hồi từ người bán sản phẩm
   */
  isSellerReply?: boolean | null;
  /**
   * Đánh dấu phản hồi từ quản trị viên
   */
  isAdminReply?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Hệ thống yêu cầu hỗ trợ và khiếu nại tài nguyên kỹ thuật số (FLOW-U09 & FR-23)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tickets".
 */
export interface Ticket {
  id: number;
  /**
   * Mã định danh khiếu nại duy nhất (VD: TCK-YYYYMMDD-XXXXXX)
   */
  code: string;
  /**
   * Người dùng gửi yêu cầu hỗ trợ / khiếu nại
   */
  user: number | User;
  /**
   * Người bán liên quan đến sản phẩm được khiếu nại
   */
  seller?: (number | null) | User;
  /**
   * Đơn hàng liên quan (nếu có)
   */
  order?: (number | null) | Order;
  /**
   * Sản phẩm liên quan đến sự cố
   */
  product?: (number | null) | Product;
  /**
   * Phân loại lý do khiếu nại
   */
  reason: 'FILE_CORRUPTED' | 'MISLEADING_CONTENT' | 'DOWNLOAD_ERROR' | 'BILLING_DISPUTE' | 'OTHER';
  /**
   * Tiêu đề ngắn gọn tóm tắt sự cố
   */
  subject: string;
  /**
   * Mô tả chi tiết sự cố gặp phải
   */
  description: string;
  /**
   * Trạng thái vòng đời hỗ trợ
   */
  status: 'OPEN' | 'IN_PROGRESS' | 'WAITING_USER' | 'RESOLVED' | 'CLOSED';
  /**
   * Mức độ ưu tiên xử lý
   */
  priority: 'LOW' | 'NORMAL' | 'HIGH' | 'URGENT';
  /**
   * Kết quả xử lý khiếu nại
   */
  resolution?: ('EXPLAINED' | 'FIX_PROVIDED' | 'REFUNDED' | 'REJECTED') | null;
  /**
   * Chuỗi tin nhắn trao đổi giữa các bên (chỉ ghi thêm, không sửa/xoá)
   */
  messages?:
    | {
        sender: number | User;
        senderRole: 'buyer' | 'seller' | 'admin';
        message: string;
        createdAt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Hồ sơ kiểm duyệt do người dùng báo cáo sản phẩm (FR-22). Moderator/Admin xem và xử lý tại đây; báo cáo không tự đổi trạng thái sản phẩm.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "moderation_cases".
 */
export interface ModerationCase {
  id: number;
  /**
   * Sản phẩm bị báo cáo
   */
  product: number | Product;
  /**
   * Người dùng đã gửi báo cáo
   */
  reporter: number | User;
  /**
   * Lý do báo cáo theo FR-22
   */
  reason:
    | 'FILE_CORRUPTED'
    | 'CONTENT_MISMATCH'
    | 'COPYRIGHT_VIOLATION'
    | 'SPAM'
    | 'PROHIBITED_CONTENT'
    | 'MISLEADING_PREVIEW'
    | 'OTHER';
  /**
   * Mô tả chi tiết (tuỳ chọn, tối đa 2000 ký tự)
   */
  description?: string | null;
  /**
   * Trạng thái xử lý hồ sơ kiểm duyệt
   */
  status: 'OPEN' | 'IN_REVIEW' | 'RESOLVED' | 'DISMISSED';
  /**
   * Kết luận / ghi chú xử lý của ban kiểm duyệt
   */
  resolutionNotes?: string | null;
  /**
   * Moderator/Admin đã xử lý hồ sơ
   */
  resolvedBy?: (number | null) | User;
  /**
   * Thời điểm xử lý
   */
  resolvedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: number;
  items?:
    | {
        product?: (number | null) | Product;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  paymentMethod?: 'stripe' | null;
  stripe?: {
    customerID?: string | null;
    paymentIntentID?: string | null;
  };
  billingAddress?: {
    title?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    company?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
    phone?: string | null;
  };
  status: 'pending' | 'succeeded' | 'failed' | 'cancelled' | 'expired' | 'refunded';
  customer?: (number | null) | User;
  customerEmail?: string | null;
  order?: (number | null) | Order;
  amount?: number | null;
  currency?: 'USD' | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'software_types';
        value: number | SoftwareType;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'product_previews';
        value: number | ProductPreview;
      } | null)
    | ({
        relationTo: 'product_files';
        value: number | ProductFile;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'seller_profiles';
        value: number | SellerProfile;
      } | null)
    | ({
        relationTo: 'wallets';
        value: number | Wallet;
      } | null)
    | ({
        relationTo: 'wallet_ledger';
        value: number | WalletLedger;
      } | null)
    | ({
        relationTo: 'payment_intents';
        value: number | PaymentIntent;
      } | null)
    | ({
        relationTo: 'payment_transactions';
        value: number | PaymentTransaction;
      } | null)
    | ({
        relationTo: 'payment_webhook_events';
        value: number | PaymentWebhookEvent;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'order_items';
        value: number | OrderItem;
      } | null)
    | ({
        relationTo: 'entitlements';
        value: number | Entitlement;
      } | null)
    | ({
        relationTo: 'download_events';
        value: number | DownloadEvent;
      } | null)
    | ({
        relationTo: 'seller_earnings';
        value: number | SellerEarning;
      } | null)
    | ({
        relationTo: 'withdrawals';
        value: number | Withdrawal;
      } | null)
    | ({
        relationTo: 'withdrawal_events';
        value: number | WithdrawalEvent;
      } | null)
    | ({
        relationTo: 'refunds';
        value: number | Refund;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'comments';
        value: number | Comment;
      } | null)
    | ({
        relationTo: 'tickets';
        value: number | Ticket;
      } | null)
    | ({
        relationTo: 'moderation_cases';
        value: number | ModerationCase;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'addresses';
        value: number | Address;
      } | null)
    | ({
        relationTo: 'transactions';
        value: number | Transaction;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  orders?: T;
  addresses?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  publishedOn?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        carousel?: T | CarouselBlockSelect<T>;
        threeItemGrid?: T | ThreeItemGridBlockSelect<T>;
        banner?: T | BannerBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselBlock_select".
 */
export interface CarouselBlockSelect<T extends boolean = true> {
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  populatedDocs?: T;
  populatedDocsTotal?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ThreeItemGridBlock_select".
 */
export interface ThreeItemGridBlockSelect<T extends boolean = true> {
  products?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock_select".
 */
export interface BannerBlockSelect<T extends boolean = true> {
  style?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  description?: T;
  parent?: T;
  icon?: T;
  image?: T;
  sortOrder?: T;
  status?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "software_types_select".
 */
export interface SoftwareTypesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  icon?: T;
  fileExtensions?: T;
  description?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product_previews_select".
 */
export interface ProductPreviewsSelect<T extends boolean = true> {
  title?: T;
  previewImage?: T;
  previewType?: T;
  isWatermarked?: T;
  caption?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product_files_select".
 */
export interface ProductFilesSelect<T extends boolean = true> {
  seller?: T;
  originalFilename?: T;
  fileFormat?: T;
  checksum?: T;
  fileSize?: T;
  virusScanStatus?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  previewGallery?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
      };
  price?: T;
  isFree?: T;
  technicalSpecs?:
    | T
    | {
        fileFormat?: T;
        softwareVersion?: T;
        fileSize?: T;
        unit?: T;
      };
  relatedProducts?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  categories?: T;
  software_types?: T;
  tags?: T;
  seller?: T;
  originalFiles?: T;
  moderationStatus?: T;
  moderationNotes?: T;
  moderationHistory?:
    | T
    | {
        reviewer?: T;
        action?: T;
        note?: T;
        timestamp?: T;
        id?: T;
      };
  copyrightDeclared?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seller_profiles_select".
 */
export interface SellerProfilesSelect<T extends boolean = true> {
  user?: T;
  displayName?: T;
  bio?: T;
  avatar?: T;
  phone?: T;
  payoutInfo?:
    | T
    | {
        bankName?: T;
        accountNumber?: T;
        accountHolderName?: T;
      };
  sellerTermsAccepted?: T;
  sellerTermsAcceptedAt?: T;
  commissionRate?: T;
  status?: T;
  totalSales?: T;
  rating?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wallets_select".
 */
export interface WalletsSelect<T extends boolean = true> {
  user?: T;
  balance?: T;
  pendingBalance?: T;
  currency?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wallet_ledger_select".
 */
export interface WalletLedgerSelect<T extends boolean = true> {
  wallet?: T;
  user?: T;
  type?: T;
  amount?: T;
  direction?: T;
  referenceType?: T;
  referenceId?: T;
  balanceBefore?: T;
  balanceAfter?: T;
  description?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment_intents_select".
 */
export interface PaymentIntentsSelect<T extends boolean = true> {
  code?: T;
  user?: T;
  provider?: T;
  amount?: T;
  currency?: T;
  status?: T;
  reconciliationFlag?: T;
  reconciliationNote?: T;
  expiresAt?: T;
  checkoutUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment_transactions_select".
 */
export interface PaymentTransactionsSelect<T extends boolean = true> {
  paymentIntent?: T;
  user?: T;
  provider?: T;
  providerTransactionId?: T;
  amount?: T;
  rawReference?: T;
  status?: T;
  paidAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment_webhook_events_select".
 */
export interface PaymentWebhookEventsSelect<T extends boolean = true> {
  provider?: T;
  eventId?: T;
  payload?: T;
  headers?: T;
  signatureValid?: T;
  status?: T;
  processedAt?: T;
  errorDetails?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  code?: T;
  buyer?: T;
  totalAmount?: T;
  currency?: T;
  status?: T;
  paymentSource?: T;
  paidAt?: T;
  notes?: T;
  items?: T;
  earnings?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order_items_select".
 */
export interface OrderItemsSelect<T extends boolean = true> {
  order?: T;
  product?: T;
  seller?: T;
  salePrice?: T;
  platformFee?: T;
  sellerAmount?: T;
  tax?: T;
  policyVersion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entitlements_select".
 */
export interface EntitlementsSelect<T extends boolean = true> {
  user?: T;
  product?: T;
  order?: T;
  orderItem?: T;
  status?: T;
  grantedAt?: T;
  downloadCount?: T;
  maxDownloads?: T;
  expiresAt?: T;
  revokedAt?: T;
  reason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "download_events_select".
 */
export interface DownloadEventsSelect<T extends boolean = true> {
  user?: T;
  product?: T;
  entitlement?: T;
  ipAddress?: T;
  userAgent?: T;
  downloadedAt?: T;
  status?: T;
  downloadTokenHash?: T;
  errorReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seller_earnings_select".
 */
export interface SellerEarningsSelect<T extends boolean = true> {
  seller?: T;
  order?: T;
  orderItem?: T;
  product?: T;
  salePrice?: T;
  platformFee?: T;
  sellerAmount?: T;
  tax?: T;
  commissionRate?: T;
  currency?: T;
  status?: T;
  holdPeriodDays?: T;
  holdUntil?: T;
  availableAt?: T;
  paidAt?: T;
  reversedAt?: T;
  policyVersion?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "withdrawals_select".
 */
export interface WithdrawalsSelect<T extends boolean = true> {
  code?: T;
  seller?: T;
  amount?: T;
  currency?: T;
  status?: T;
  bankInfo?:
    | T
    | {
        bankName?: T;
        accountNumber?: T;
        accountHolderName?: T;
      };
  requestedAt?: T;
  reviewedAt?: T;
  reviewedBy?: T;
  paidAt?: T;
  rejectionReason?: T;
  failureReason?: T;
  notes?: T;
  events?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "withdrawal_events_select".
 */
export interface WithdrawalEventsSelect<T extends boolean = true> {
  withdrawal?: T;
  fromStatus?: T;
  toStatus?: T;
  actor?: T;
  actorRole?: T;
  reason?: T;
  notes?: T;
  timestamp?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "refunds_select".
 */
export interface RefundsSelect<T extends boolean = true> {
  code?: T;
  order?: T;
  orderItem?: T;
  buyer?: T;
  seller?: T;
  amount?: T;
  platformFeeRefunded?: T;
  sellerAmountRefunded?: T;
  currency?: T;
  reason?: T;
  status?: T;
  processedBy?: T;
  ledgerTransaction?: T;
  entitlementRevoked?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  product?: T;
  user?: T;
  entitlement?: T;
  rating?: T;
  title?: T;
  content?: T;
  status?: T;
  sellerReply?:
    | T
    | {
        comment?: T;
        repliedAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments_select".
 */
export interface CommentsSelect<T extends boolean = true> {
  product?: T;
  user?: T;
  parent?: T;
  content?: T;
  status?: T;
  isSellerReply?: T;
  isAdminReply?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tickets_select".
 */
export interface TicketsSelect<T extends boolean = true> {
  code?: T;
  user?: T;
  seller?: T;
  order?: T;
  product?: T;
  reason?: T;
  subject?: T;
  description?: T;
  status?: T;
  priority?: T;
  resolution?: T;
  messages?:
    | T
    | {
        sender?: T;
        senderRole?: T;
        message?: T;
        createdAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "moderation_cases_select".
 */
export interface ModerationCasesSelect<T extends boolean = true> {
  product?: T;
  reporter?: T;
  reason?: T;
  description?: T;
  status?: T;
  resolutionNotes?: T;
  resolvedBy?: T;
  resolvedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses_select".
 */
export interface AddressesSelect<T extends boolean = true> {
  customer?: T;
  title?: T;
  firstName?: T;
  lastName?: T;
  company?: T;
  addressLine1?: T;
  addressLine2?: T;
  city?: T;
  state?: T;
  postalCode?: T;
  country?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        quantity?: T;
        id?: T;
      };
  paymentMethod?: T;
  stripe?:
    | T
    | {
        customerID?: T;
        paymentIntentID?: T;
      };
  billingAddress?:
    | T
    | {
        title?: T;
        firstName?: T;
        lastName?: T;
        company?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  status?: T;
  customer?: T;
  customerEmail?: T;
  order?: T;
  amount?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commission_settings".
 */
export interface CommissionSetting {
  id: number;
  /**
   * Tỷ lệ hoa hồng mặc định của sàn (0.0 - 1.0, mặc định: 0.30 tức 30%)
   */
  defaultRate: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commission_settings_select".
 */
export interface CommissionSettingsSelect<T extends boolean = true> {
  defaultRate?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}